
services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_DATA: /data/postgres
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      # PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5532:5432"


# services:
#   postgres:
#     container_name: postgres_go
#     image: postgres:16.4
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: my_pass
#       PGDATA: /data/postgres
#     volumes:
#       - ./postgres-data:/data/postgres    
#     ports:
#       - "5423:5432"


#   adminer:
#     image: adminer
#     ports:
#     - 8080:8080